name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 1.0.0
homepage: https://github.com/huangred/video_trimmer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^2.0.0
#  video_player: ^0.11.0
  cached_video_player: ^1.0.3
  flutter_ffmpeg: ^0.3.0
  video_thumbnail: ^0.2.1
  path_provider: ^1.6.7
  intl: ^0.16.1
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
